# Generated by Django 5.0.1 on 2024-02-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuild', '0003_category_alter_project_category_delete_userresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
